//! Machine-checked ABI layout assertions.
//!
//! Generated by `pina migrations create`. Do not edit.
//!
//! Run `pina migrations create` after changing a schema; `pina migrations
//! check` fails when this file no longer matches the manifest. A layout
//! change that forgets an offset fails `cargo test` in the same change.

// manifest-sha256: 2d8d9565dfb05467457f1b010a536d0a91ec75eb64431e7834eafb5d8cf245ee
// program-id: pAMMvXaqR2VVFqznf6dgvUFQjLXXAEeL9cb48cXsGeV
// version_type: u8

#![allow(clippy::identity_op, clippy::eq_op)]
#![allow(clippy::unreadable_literal)]

/// Program id recorded in the manifest.
pub const PROGRAM_ID: &str = "pAMMvXaqR2VVFqznf6dgvUFQjLXXAEeL9cb48cXsGeV";

/// ABI layout for the `AmmConfig` account.
pub mod account_1_01 {
	/// Manifest contract key.
	pub const KEY: &str = "account:1:01";
	/// Rust type name as declared in the program.
	pub const RUST_NAME: &str = "AmmConfig";
	/// Current schema version.
	pub const VERSION: u32 = 0;
	/// Schema hash recorded for this version.
	pub const SCHEMA_SHA256: &str = "c4662bd7da986a8574e958848772303c91c3191aec94bc8a45831623b2fc60b6";
	/// Width of the discriminator in bytes.
	pub const DISCRIMINATOR_BYTES: usize = 1;
	/// Byte offset of the migration version field.
	pub const VERSION_OFFSET: usize = 1;
	/// Width of the migration version field in bytes; zero without an envelope.
	pub const VERSION_BYTES: usize = 1;
	/// Bytes occupied by the discriminator and version envelope together.
	pub const MIGRATION_HEADER_SIZE: usize = 2;
	/// Payload size in bytes, excluding the envelope header.
	pub const PAYLOAD_SIZE: usize = 79;
	/// Total encoded size in bytes, including the envelope header.
	pub const SIZE: usize = MIGRATION_HEADER_SIZE + PAYLOAD_SIZE;
	/// Manifest payload size; must agree with `PAYLOAD_SIZE`.
	pub const MANIFEST_PAYLOAD_SIZE: usize = 79;
	/// `(name, absolute_offset, size)` in encoded bytes.
	pub const FIELDS: &[(&str, usize, usize)] = &[
		("authority", MIGRATION_HEADER_SIZE + 0, 32),
		("pool_creator_authority", MIGRATION_HEADER_SIZE + 32, 32),
		("trade_fee_rate", MIGRATION_HEADER_SIZE + 64, 4),
		("protocol_fee_rate", MIGRATION_HEADER_SIZE + 68, 4),
		("creator_fee_rate", MIGRATION_HEADER_SIZE + 72, 4),
		("index", MIGRATION_HEADER_SIZE + 76, 2),
		("bump", MIGRATION_HEADER_SIZE + 78, 1),
	];
}

/// ABI layout for the `Pool` account.
pub mod account_1_02 {
	/// Manifest contract key.
	pub const KEY: &str = "account:1:02";
	/// Rust type name as declared in the program.
	pub const RUST_NAME: &str = "Pool";
	/// Current schema version.
	pub const VERSION: u32 = 0;
	/// Schema hash recorded for this version.
	pub const SCHEMA_SHA256: &str = "de3580159bbd56c5b528db499c82b91b5b3f9b10fbfe84e7b9aa67ad7408914d";
	/// Width of the discriminator in bytes.
	pub const DISCRIMINATOR_BYTES: usize = 1;
	/// Byte offset of the migration version field.
	pub const VERSION_OFFSET: usize = 1;
	/// Width of the migration version field in bytes; zero without an envelope.
	pub const VERSION_BYTES: usize = 1;
	/// Bytes occupied by the discriminator and version envelope together.
	pub const MIGRATION_HEADER_SIZE: usize = 2;
	/// Payload size in bytes, excluding the envelope header.
	pub const PAYLOAD_SIZE: usize = 278;
	/// Total encoded size in bytes, including the envelope header.
	pub const SIZE: usize = MIGRATION_HEADER_SIZE + PAYLOAD_SIZE;
	/// Manifest payload size; must agree with `PAYLOAD_SIZE`.
	pub const MANIFEST_PAYLOAD_SIZE: usize = 278;
	/// `(name, absolute_offset, size)` in encoded bytes.
	pub const FIELDS: &[(&str, usize, usize)] = &[
		("amm_config", MIGRATION_HEADER_SIZE + 0, 32),
		("creator", MIGRATION_HEADER_SIZE + 32, 32),
		("mint_0", MIGRATION_HEADER_SIZE + 64, 32),
		("mint_1", MIGRATION_HEADER_SIZE + 96, 32),
		("vault_0", MIGRATION_HEADER_SIZE + 128, 32),
		("vault_1", MIGRATION_HEADER_SIZE + 160, 32),
		("lp_mint", MIGRATION_HEADER_SIZE + 192, 32),
		("lp_supply", MIGRATION_HEADER_SIZE + 224, 8),
		("protocol_fees_0", MIGRATION_HEADER_SIZE + 232, 8),
		("protocol_fees_1", MIGRATION_HEADER_SIZE + 240, 8),
		("creator_fees_0", MIGRATION_HEADER_SIZE + 248, 8),
		("creator_fees_1", MIGRATION_HEADER_SIZE + 256, 8),
		("trade_fee_rate", MIGRATION_HEADER_SIZE + 264, 4),
		("protocol_fee_rate", MIGRATION_HEADER_SIZE + 268, 4),
		("creator_fee_rate", MIGRATION_HEADER_SIZE + 272, 4),
		("creator_fee_mode", MIGRATION_HEADER_SIZE + 276, 1),
		("bump", MIGRATION_HEADER_SIZE + 277, 1),
	];
}

/// ABI layout for the `PoolCreated` event.
pub mod event_1_01 {
	/// Manifest contract key.
	pub const KEY: &str = "event:1:01";
	/// Rust type name as declared in the program.
	pub const RUST_NAME: &str = "PoolCreated";
	/// Current schema version.
	pub const VERSION: u32 = 0;
	/// Schema hash recorded for this version.
	pub const SCHEMA_SHA256: &str = "eaf7a6486a275cb34b0b0fdf2de38243e0c7c10441b902d6825d51f1b3c67998";
	/// Width of the discriminator in bytes.
	pub const DISCRIMINATOR_BYTES: usize = 1;
	/// Byte offset of the migration version field.
	pub const VERSION_OFFSET: usize = 1;
	/// Width of the migration version field in bytes; zero without an envelope.
	pub const VERSION_BYTES: usize = 1;
	/// Bytes occupied by the discriminator and version envelope together.
	pub const MIGRATION_HEADER_SIZE: usize = 2;
	/// Payload size in bytes, excluding the envelope header.
	pub const PAYLOAD_SIZE: usize = 216;
	/// Total encoded size in bytes, including the envelope header.
	pub const SIZE: usize = MIGRATION_HEADER_SIZE + PAYLOAD_SIZE;
	/// Manifest payload size; must agree with `PAYLOAD_SIZE`.
	pub const MANIFEST_PAYLOAD_SIZE: usize = 216;
	/// `(name, absolute_offset, size)` in encoded bytes.
	pub const FIELDS: &[(&str, usize, usize)] = &[
		("pool", MIGRATION_HEADER_SIZE + 0, 32),
		("amm_config", MIGRATION_HEADER_SIZE + 32, 32),
		("creator", MIGRATION_HEADER_SIZE + 64, 32),
		("mint_0", MIGRATION_HEADER_SIZE + 96, 32),
		("mint_1", MIGRATION_HEADER_SIZE + 128, 32),
		("lp_mint", MIGRATION_HEADER_SIZE + 160, 32),
		("amount_0", MIGRATION_HEADER_SIZE + 192, 8),
		("amount_1", MIGRATION_HEADER_SIZE + 200, 8),
		("lp_supply", MIGRATION_HEADER_SIZE + 208, 8),
	];
}

/// ABI layout for the `Swapped` event.
pub mod event_1_02 {
	/// Manifest contract key.
	pub const KEY: &str = "event:1:02";
	/// Rust type name as declared in the program.
	pub const RUST_NAME: &str = "Swapped";
	/// Current schema version.
	pub const VERSION: u32 = 0;
	/// Schema hash recorded for this version.
	pub const SCHEMA_SHA256: &str = "06fa8694da15b617c00a38ef963590a015233438a507818b54be6f6c03b61913";
	/// Width of the discriminator in bytes.
	pub const DISCRIMINATOR_BYTES: usize = 1;
	/// Byte offset of the migration version field.
	pub const VERSION_OFFSET: usize = 1;
	/// Width of the migration version field in bytes; zero without an envelope.
	pub const VERSION_BYTES: usize = 1;
	/// Bytes occupied by the discriminator and version envelope together.
	pub const MIGRATION_HEADER_SIZE: usize = 2;
	/// Payload size in bytes, excluding the envelope header.
	pub const PAYLOAD_SIZE: usize = 122;
	/// Total encoded size in bytes, including the envelope header.
	pub const SIZE: usize = MIGRATION_HEADER_SIZE + PAYLOAD_SIZE;
	/// Manifest payload size; must agree with `PAYLOAD_SIZE`.
	pub const MANIFEST_PAYLOAD_SIZE: usize = 122;
	/// `(name, absolute_offset, size)` in encoded bytes.
	pub const FIELDS: &[(&str, usize, usize)] = &[
		("pool", MIGRATION_HEADER_SIZE + 0, 32),
		("trader", MIGRATION_HEADER_SIZE + 32, 32),
		("zero_for_one", MIGRATION_HEADER_SIZE + 64, 1),
		("amount_in", MIGRATION_HEADER_SIZE + 65, 8),
		("amount_out", MIGRATION_HEADER_SIZE + 73, 8),
		("trade_fee", MIGRATION_HEADER_SIZE + 81, 8),
		("protocol_fee", MIGRATION_HEADER_SIZE + 89, 8),
		("creator_fee", MIGRATION_HEADER_SIZE + 97, 8),
		("creator_fee_on_input", MIGRATION_HEADER_SIZE + 105, 1),
		("reserve_0", MIGRATION_HEADER_SIZE + 106, 8),
		("reserve_1", MIGRATION_HEADER_SIZE + 114, 8),
	];
}

/// ABI layout for the `LiquidityChanged` event.
pub mod event_1_03 {
	/// Manifest contract key.
	pub const KEY: &str = "event:1:03";
	/// Rust type name as declared in the program.
	pub const RUST_NAME: &str = "LiquidityChanged";
	/// Current schema version.
	pub const VERSION: u32 = 0;
	/// Schema hash recorded for this version.
	pub const SCHEMA_SHA256: &str = "bae981de1dd0b7f03bc0989f3ce6e2491b49e92084db0428979822c8eb770bfd";
	/// Width of the discriminator in bytes.
	pub const DISCRIMINATOR_BYTES: usize = 1;
	/// Byte offset of the migration version field.
	pub const VERSION_OFFSET: usize = 1;
	/// Width of the migration version field in bytes; zero without an envelope.
	pub const VERSION_BYTES: usize = 1;
	/// Bytes occupied by the discriminator and version envelope together.
	pub const MIGRATION_HEADER_SIZE: usize = 2;
	/// Payload size in bytes, excluding the envelope header.
	pub const PAYLOAD_SIZE: usize = 97;
	/// Total encoded size in bytes, including the envelope header.
	pub const SIZE: usize = MIGRATION_HEADER_SIZE + PAYLOAD_SIZE;
	/// Manifest payload size; must agree with `PAYLOAD_SIZE`.
	pub const MANIFEST_PAYLOAD_SIZE: usize = 97;
	/// `(name, absolute_offset, size)` in encoded bytes.
	pub const FIELDS: &[(&str, usize, usize)] = &[
		("pool", MIGRATION_HEADER_SIZE + 0, 32),
		("owner", MIGRATION_HEADER_SIZE + 32, 32),
		("is_deposit", MIGRATION_HEADER_SIZE + 64, 1),
		("lp_amount", MIGRATION_HEADER_SIZE + 65, 8),
		("amount_0", MIGRATION_HEADER_SIZE + 73, 8),
		("amount_1", MIGRATION_HEADER_SIZE + 81, 8),
		("lp_supply", MIGRATION_HEADER_SIZE + 89, 8),
	];
}

/// ABI layout for the `FeesCollected` event.
pub mod event_1_04 {
	/// Manifest contract key.
	pub const KEY: &str = "event:1:04";
	/// Rust type name as declared in the program.
	pub const RUST_NAME: &str = "FeesCollected";
	/// Current schema version.
	pub const VERSION: u32 = 0;
	/// Schema hash recorded for this version.
	pub const SCHEMA_SHA256: &str = "289f984edbe0c827908926ec4cf5059249ca4de5da155802328fc36234a130e5";
	/// Width of the discriminator in bytes.
	pub const DISCRIMINATOR_BYTES: usize = 1;
	/// Byte offset of the migration version field.
	pub const VERSION_OFFSET: usize = 1;
	/// Width of the migration version field in bytes; zero without an envelope.
	pub const VERSION_BYTES: usize = 1;
	/// Bytes occupied by the discriminator and version envelope together.
	pub const MIGRATION_HEADER_SIZE: usize = 2;
	/// Payload size in bytes, excluding the envelope header.
	pub const PAYLOAD_SIZE: usize = 81;
	/// Total encoded size in bytes, including the envelope header.
	pub const SIZE: usize = MIGRATION_HEADER_SIZE + PAYLOAD_SIZE;
	/// Manifest payload size; must agree with `PAYLOAD_SIZE`.
	pub const MANIFEST_PAYLOAD_SIZE: usize = 81;
	/// `(name, absolute_offset, size)` in encoded bytes.
	pub const FIELDS: &[(&str, usize, usize)] = &[
		("pool", MIGRATION_HEADER_SIZE + 0, 32),
		("collector", MIGRATION_HEADER_SIZE + 32, 32),
		("is_protocol", MIGRATION_HEADER_SIZE + 64, 1),
		("amount_0", MIGRATION_HEADER_SIZE + 65, 8),
		("amount_1", MIGRATION_HEADER_SIZE + 73, 8),
	];
}

/// ABI layout for the `CreateConfigInstruction` instruction.
pub mod instruction_1_00 {
	/// Manifest contract key.
	pub const KEY: &str = "instruction:1:00";
	/// Rust type name as declared in the program.
	pub const RUST_NAME: &str = "CreateConfigInstruction";
	/// Current schema version.
	pub const VERSION: u32 = 0;
	/// Schema hash recorded for this version.
	pub const SCHEMA_SHA256: &str = "9dedacb703e2b0775c3ccc60702ab4f5a768d6392302b418069c1e8846b5dcf3";
	/// Width of the discriminator in bytes.
	pub const DISCRIMINATOR_BYTES: usize = 1;
	/// Byte offset of the migration version field.
	pub const VERSION_OFFSET: usize = 1;
	/// Width of the migration version field in bytes; zero without an envelope.
	pub const VERSION_BYTES: usize = 0;
	/// Bytes occupied by the discriminator and version envelope together.
	pub const MIGRATION_HEADER_SIZE: usize = 1;
	/// Payload size in bytes, excluding the envelope header.
	pub const PAYLOAD_SIZE: usize = 78;
	/// Total encoded size in bytes, including the envelope header.
	pub const SIZE: usize = MIGRATION_HEADER_SIZE + PAYLOAD_SIZE;
	/// Manifest payload size; must agree with `PAYLOAD_SIZE`.
	pub const MANIFEST_PAYLOAD_SIZE: usize = 78;
	/// `(name, absolute_offset, size)` in encoded bytes.
	pub const FIELDS: &[(&str, usize, usize)] = &[
		("index", MIGRATION_HEADER_SIZE + 0, 2),
		("trade_fee_rate", MIGRATION_HEADER_SIZE + 2, 4),
		("protocol_fee_rate", MIGRATION_HEADER_SIZE + 6, 4),
		("creator_fee_rate", MIGRATION_HEADER_SIZE + 10, 4),
		("authority", MIGRATION_HEADER_SIZE + 14, 32),
		("pool_creator_authority", MIGRATION_HEADER_SIZE + 46, 32),
	];
}

/// ABI layout for the `UpdateConfigInstruction` instruction.
pub mod instruction_1_01 {
	/// Manifest contract key.
	pub const KEY: &str = "instruction:1:01";
	/// Rust type name as declared in the program.
	pub const RUST_NAME: &str = "UpdateConfigInstruction";
	/// Current schema version.
	pub const VERSION: u32 = 0;
	/// Schema hash recorded for this version.
	pub const SCHEMA_SHA256: &str = "ddcacee7cd3f3705dd4714824d75df6fd2d043df684c5a202b748c9419ba437c";
	/// Width of the discriminator in bytes.
	pub const DISCRIMINATOR_BYTES: usize = 1;
	/// Byte offset of the migration version field.
	pub const VERSION_OFFSET: usize = 1;
	/// Width of the migration version field in bytes; zero without an envelope.
	pub const VERSION_BYTES: usize = 0;
	/// Bytes occupied by the discriminator and version envelope together.
	pub const MIGRATION_HEADER_SIZE: usize = 1;
	/// Payload size in bytes, excluding the envelope header.
	pub const PAYLOAD_SIZE: usize = 44;
	/// Total encoded size in bytes, including the envelope header.
	pub const SIZE: usize = MIGRATION_HEADER_SIZE + PAYLOAD_SIZE;
	/// Manifest payload size; must agree with `PAYLOAD_SIZE`.
	pub const MANIFEST_PAYLOAD_SIZE: usize = 44;
	/// `(name, absolute_offset, size)` in encoded bytes.
	pub const FIELDS: &[(&str, usize, usize)] = &[
		("new_authority", MIGRATION_HEADER_SIZE + 0, 32),
		("trade_fee_rate", MIGRATION_HEADER_SIZE + 32, 4),
		("protocol_fee_rate", MIGRATION_HEADER_SIZE + 36, 4),
		("creator_fee_rate", MIGRATION_HEADER_SIZE + 40, 4),
	];
}

/// ABI layout for the `CreatePoolInstruction` instruction.
pub mod instruction_1_02 {
	/// Manifest contract key.
	pub const KEY: &str = "instruction:1:02";
	/// Rust type name as declared in the program.
	pub const RUST_NAME: &str = "CreatePoolInstruction";
	/// Current schema version.
	pub const VERSION: u32 = 0;
	/// Schema hash recorded for this version.
	pub const SCHEMA_SHA256: &str = "66b369346cedc65c7ff9ba4e3726123f50eab0ae4142f9d66962c56d9efa2a73";
	/// Width of the discriminator in bytes.
	pub const DISCRIMINATOR_BYTES: usize = 1;
	/// Byte offset of the migration version field.
	pub const VERSION_OFFSET: usize = 1;
	/// Width of the migration version field in bytes; zero without an envelope.
	pub const VERSION_BYTES: usize = 0;
	/// Bytes occupied by the discriminator and version envelope together.
	pub const MIGRATION_HEADER_SIZE: usize = 1;
	/// Payload size in bytes, excluding the envelope header.
	pub const PAYLOAD_SIZE: usize = 49;
	/// Total encoded size in bytes, including the envelope header.
	pub const SIZE: usize = MIGRATION_HEADER_SIZE + PAYLOAD_SIZE;
	/// Manifest payload size; must agree with `PAYLOAD_SIZE`.
	pub const MANIFEST_PAYLOAD_SIZE: usize = 49;
	/// `(name, absolute_offset, size)` in encoded bytes.
	pub const FIELDS: &[(&str, usize, usize)] = &[
		("amount_0", MIGRATION_HEADER_SIZE + 0, 8),
		("amount_1", MIGRATION_HEADER_SIZE + 8, 8),
		("creator", MIGRATION_HEADER_SIZE + 16, 32),
		("creator_fee_mode", MIGRATION_HEADER_SIZE + 48, 1),
	];
}

/// ABI layout for the `DepositInstruction` instruction.
pub mod instruction_1_03 {
	/// Manifest contract key.
	pub const KEY: &str = "instruction:1:03";
	/// Rust type name as declared in the program.
	pub const RUST_NAME: &str = "DepositInstruction";
	/// Current schema version.
	pub const VERSION: u32 = 0;
	/// Schema hash recorded for this version.
	pub const SCHEMA_SHA256: &str = "83aa7201e807f036862cd446e72495a5ea96a477dc96e79da1e068bcc8e58eb3";
	/// Width of the discriminator in bytes.
	pub const DISCRIMINATOR_BYTES: usize = 1;
	/// Byte offset of the migration version field.
	pub const VERSION_OFFSET: usize = 1;
	/// Width of the migration version field in bytes; zero without an envelope.
	pub const VERSION_BYTES: usize = 0;
	/// Bytes occupied by the discriminator and version envelope together.
	pub const MIGRATION_HEADER_SIZE: usize = 1;
	/// Payload size in bytes, excluding the envelope header.
	pub const PAYLOAD_SIZE: usize = 24;
	/// Total encoded size in bytes, including the envelope header.
	pub const SIZE: usize = MIGRATION_HEADER_SIZE + PAYLOAD_SIZE;
	/// Manifest payload size; must agree with `PAYLOAD_SIZE`.
	pub const MANIFEST_PAYLOAD_SIZE: usize = 24;
	/// `(name, absolute_offset, size)` in encoded bytes.
	pub const FIELDS: &[(&str, usize, usize)] = &[
		("lp_amount", MIGRATION_HEADER_SIZE + 0, 8),
		("maximum_amount_0", MIGRATION_HEADER_SIZE + 8, 8),
		("maximum_amount_1", MIGRATION_HEADER_SIZE + 16, 8),
	];
}

/// ABI layout for the `WithdrawInstruction` instruction.
pub mod instruction_1_04 {
	/// Manifest contract key.
	pub const KEY: &str = "instruction:1:04";
	/// Rust type name as declared in the program.
	pub const RUST_NAME: &str = "WithdrawInstruction";
	/// Current schema version.
	pub const VERSION: u32 = 0;
	/// Schema hash recorded for this version.
	pub const SCHEMA_SHA256: &str = "aff62d6f11058a9f387bedb82841667be8a75c6de077be36ae92b0999670e8b0";
	/// Width of the discriminator in bytes.
	pub const DISCRIMINATOR_BYTES: usize = 1;
	/// Byte offset of the migration version field.
	pub const VERSION_OFFSET: usize = 1;
	/// Width of the migration version field in bytes; zero without an envelope.
	pub const VERSION_BYTES: usize = 0;
	/// Bytes occupied by the discriminator and version envelope together.
	pub const MIGRATION_HEADER_SIZE: usize = 1;
	/// Payload size in bytes, excluding the envelope header.
	pub const PAYLOAD_SIZE: usize = 24;
	/// Total encoded size in bytes, including the envelope header.
	pub const SIZE: usize = MIGRATION_HEADER_SIZE + PAYLOAD_SIZE;
	/// Manifest payload size; must agree with `PAYLOAD_SIZE`.
	pub const MANIFEST_PAYLOAD_SIZE: usize = 24;
	/// `(name, absolute_offset, size)` in encoded bytes.
	pub const FIELDS: &[(&str, usize, usize)] = &[
		("lp_amount", MIGRATION_HEADER_SIZE + 0, 8),
		("minimum_amount_0", MIGRATION_HEADER_SIZE + 8, 8),
		("minimum_amount_1", MIGRATION_HEADER_SIZE + 16, 8),
	];
}

/// ABI layout for the `SwapExactInInstruction` instruction.
pub mod instruction_1_05 {
	/// Manifest contract key.
	pub const KEY: &str = "instruction:1:05";
	/// Rust type name as declared in the program.
	pub const RUST_NAME: &str = "SwapExactInInstruction";
	/// Current schema version.
	pub const VERSION: u32 = 0;
	/// Schema hash recorded for this version.
	pub const SCHEMA_SHA256: &str = "aad9be16a641f0aadb7f25340c38891c8adb4f7162d5badb9d07c75092bd5f78";
	/// Width of the discriminator in bytes.
	pub const DISCRIMINATOR_BYTES: usize = 1;
	/// Byte offset of the migration version field.
	pub const VERSION_OFFSET: usize = 1;
	/// Width of the migration version field in bytes; zero without an envelope.
	pub const VERSION_BYTES: usize = 0;
	/// Bytes occupied by the discriminator and version envelope together.
	pub const MIGRATION_HEADER_SIZE: usize = 1;
	/// Payload size in bytes, excluding the envelope header.
	pub const PAYLOAD_SIZE: usize = 16;
	/// Total encoded size in bytes, including the envelope header.
	pub const SIZE: usize = MIGRATION_HEADER_SIZE + PAYLOAD_SIZE;
	/// Manifest payload size; must agree with `PAYLOAD_SIZE`.
	pub const MANIFEST_PAYLOAD_SIZE: usize = 16;
	/// `(name, absolute_offset, size)` in encoded bytes.
	pub const FIELDS: &[(&str, usize, usize)] = &[
		("amount_in", MIGRATION_HEADER_SIZE + 0, 8),
		("minimum_amount_out", MIGRATION_HEADER_SIZE + 8, 8),
	];
}

/// ABI layout for the `SwapExactOutInstruction` instruction.
pub mod instruction_1_06 {
	/// Manifest contract key.
	pub const KEY: &str = "instruction:1:06";
	/// Rust type name as declared in the program.
	pub const RUST_NAME: &str = "SwapExactOutInstruction";
	/// Current schema version.
	pub const VERSION: u32 = 0;
	/// Schema hash recorded for this version.
	pub const SCHEMA_SHA256: &str = "46f4c966d40a43194badf5f0256422b3f85f6e00770da385e98ff658626fa8d4";
	/// Width of the discriminator in bytes.
	pub const DISCRIMINATOR_BYTES: usize = 1;
	/// Byte offset of the migration version field.
	pub const VERSION_OFFSET: usize = 1;
	/// Width of the migration version field in bytes; zero without an envelope.
	pub const VERSION_BYTES: usize = 0;
	/// Bytes occupied by the discriminator and version envelope together.
	pub const MIGRATION_HEADER_SIZE: usize = 1;
	/// Payload size in bytes, excluding the envelope header.
	pub const PAYLOAD_SIZE: usize = 16;
	/// Total encoded size in bytes, including the envelope header.
	pub const SIZE: usize = MIGRATION_HEADER_SIZE + PAYLOAD_SIZE;
	/// Manifest payload size; must agree with `PAYLOAD_SIZE`.
	pub const MANIFEST_PAYLOAD_SIZE: usize = 16;
	/// `(name, absolute_offset, size)` in encoded bytes.
	pub const FIELDS: &[(&str, usize, usize)] = &[
		("amount_out", MIGRATION_HEADER_SIZE + 0, 8),
		("maximum_amount_in", MIGRATION_HEADER_SIZE + 8, 8),
	];
}

/// ABI layout for the `CollectProtocolFeesInstruction` instruction.
pub mod instruction_1_07 {
	/// Manifest contract key.
	pub const KEY: &str = "instruction:1:07";
	/// Rust type name as declared in the program.
	pub const RUST_NAME: &str = "CollectProtocolFeesInstruction";
	/// Current schema version.
	pub const VERSION: u32 = 0;
	/// Schema hash recorded for this version.
	pub const SCHEMA_SHA256: &str = "1c81938e36269b716e28ffc2ffbbb9ec1bdde3c27006e579bc635186c47534cf";
	/// Width of the discriminator in bytes.
	pub const DISCRIMINATOR_BYTES: usize = 1;
	/// Byte offset of the migration version field.
	pub const VERSION_OFFSET: usize = 1;
	/// Width of the migration version field in bytes; zero without an envelope.
	pub const VERSION_BYTES: usize = 0;
	/// Bytes occupied by the discriminator and version envelope together.
	pub const MIGRATION_HEADER_SIZE: usize = 1;
	/// Payload size in bytes, excluding the envelope header.
	pub const PAYLOAD_SIZE: usize = 16;
	/// Total encoded size in bytes, including the envelope header.
	pub const SIZE: usize = MIGRATION_HEADER_SIZE + PAYLOAD_SIZE;
	/// Manifest payload size; must agree with `PAYLOAD_SIZE`.
	pub const MANIFEST_PAYLOAD_SIZE: usize = 16;
	/// `(name, absolute_offset, size)` in encoded bytes.
	pub const FIELDS: &[(&str, usize, usize)] = &[
		("maximum_amount_0", MIGRATION_HEADER_SIZE + 0, 8),
		("maximum_amount_1", MIGRATION_HEADER_SIZE + 8, 8),
	];
}

/// ABI layout for the `CollectCreatorFeesInstruction` instruction.
pub mod instruction_1_08 {
	/// Manifest contract key.
	pub const KEY: &str = "instruction:1:08";
	/// Rust type name as declared in the program.
	pub const RUST_NAME: &str = "CollectCreatorFeesInstruction";
	/// Current schema version.
	pub const VERSION: u32 = 0;
	/// Schema hash recorded for this version.
	pub const SCHEMA_SHA256: &str = "1c81938e36269b716e28ffc2ffbbb9ec1bdde3c27006e579bc635186c47534cf";
	/// Width of the discriminator in bytes.
	pub const DISCRIMINATOR_BYTES: usize = 1;
	/// Byte offset of the migration version field.
	pub const VERSION_OFFSET: usize = 1;
	/// Width of the migration version field in bytes; zero without an envelope.
	pub const VERSION_BYTES: usize = 0;
	/// Bytes occupied by the discriminator and version envelope together.
	pub const MIGRATION_HEADER_SIZE: usize = 1;
	/// Payload size in bytes, excluding the envelope header.
	pub const PAYLOAD_SIZE: usize = 16;
	/// Total encoded size in bytes, including the envelope header.
	pub const SIZE: usize = MIGRATION_HEADER_SIZE + PAYLOAD_SIZE;
	/// Manifest payload size; must agree with `PAYLOAD_SIZE`.
	pub const MANIFEST_PAYLOAD_SIZE: usize = 16;
	/// `(name, absolute_offset, size)` in encoded bytes.
	pub const FIELDS: &[(&str, usize, usize)] = &[
		("maximum_amount_0", MIGRATION_HEADER_SIZE + 0, 8),
		("maximum_amount_1", MIGRATION_HEADER_SIZE + 8, 8),
	];
}

/// ABI layout for the `SetPoolCreatorInstruction` instruction.
pub mod instruction_1_09 {
	/// Manifest contract key.
	pub const KEY: &str = "instruction:1:09";
	/// Rust type name as declared in the program.
	pub const RUST_NAME: &str = "SetPoolCreatorInstruction";
	/// Current schema version.
	pub const VERSION: u32 = 0;
	/// Schema hash recorded for this version.
	pub const SCHEMA_SHA256: &str = "9b9c5ef5e5266080f0261fd34ef26aa5f6241805a705d856e6ac34aee990320f";
	/// Width of the discriminator in bytes.
	pub const DISCRIMINATOR_BYTES: usize = 1;
	/// Byte offset of the migration version field.
	pub const VERSION_OFFSET: usize = 1;
	/// Width of the migration version field in bytes; zero without an envelope.
	pub const VERSION_BYTES: usize = 0;
	/// Bytes occupied by the discriminator and version envelope together.
	pub const MIGRATION_HEADER_SIZE: usize = 1;
	/// Payload size in bytes, excluding the envelope header.
	pub const PAYLOAD_SIZE: usize = 32;
	/// Total encoded size in bytes, including the envelope header.
	pub const SIZE: usize = MIGRATION_HEADER_SIZE + PAYLOAD_SIZE;
	/// Manifest payload size; must agree with `PAYLOAD_SIZE`.
	pub const MANIFEST_PAYLOAD_SIZE: usize = 32;
	/// `(name, absolute_offset, size)` in encoded bytes.
	pub const FIELDS: &[(&str, usize, usize)] = &[
		("new_creator", MIGRATION_HEADER_SIZE + 0, 32),
	];
}

